baseurl: https://JohnAzeipieai.github.io
languageCode: fr
theme: terminal
paginate: 5
# Raw HTML in Markdown
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false
params:
  contentTypeName: posts
  themeColor: green
  showMenuItems: 2
  showLanguageSelector: false
  fullWidthTheme: true
  centerTheme: false
  autoCover: false
  showLastUpdated: false
  twitter:
    creator: "TimotheChauvet"
    site: ""
languages:
  en:
    languageName: English
    title: 46000% Sport
    subtitle: L'actu sportive
    owner: ""
    keywords: ""
    copyright: ""
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    missingContentMessage: Page not found...
    missingBackButtonLabel: Back to home page
    minuteReadingTime: min read
    words: words
    params:
      logo:
        logoText: Terminal
        logoHomeLink: /
    menu:
      main:
        - identifier: about
          name: 46000% sport
          url: /about
        - identifier: showcase
          name: L'actualité
          url: /showcase